name: ToDo
description: タスクを登録します
title: "[TODO] "
labels:
  - todo

body:
  - type: input
    id: summary
    attributes:
      label: タスク名
      description: Googleカレンダーの予定名になります。
    validations:
      required: true

  - type: input
    id: start
    attributes:
      label: 開始日時
      description: YYYY-MM-DD HH:mm
    validations:
      required: true

  - type: input
    id: end
    attributes:
      label: 終了日時
      description: YYYY-MM-DD HH:mm
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 詳細
      description: 必要に応じて記入してください。
