name: ToDo
description: タスクを登録します
title: "[TODO] "
labels:
  - todo

body:
  - type: input
    id: summary
    attributes:
      label: タスク名
      description: Googleカレンダーの予定名になります。
    validations:
      required: true

  - type: input
    id: start
    attributes:
      label: 開始日時
      description: YYYY-MM-DD HH:mm
    validations:
      required: true

  - type: dropdown
    id: duration
    attributes:
      label: 所要時間
      default: 2
      options:
        - "15分"
        - "30分"
        - "1時間"
        - "2時間"
        - "3時間"
        - "半日"
        - "1日"

  - type: textarea
    id: description
    attributes:
      label: 詳細
      description: 必要に応じて記入してください。
